
local armorDefs = {
	flyer = {
			"euf_angel",
			"euf_bomber",
			"euf_interceptor",
			"euf_scout",
			"euf_transport",	
			"tc_acranius",
			"tc_blade",
			"tc_dragon",
			"tc_dragonqueen",
			"tc_seeker",
			"tc_seer",
			"tc_sledgehammer",
			"tc_redeemer",			
		},

	light = {
			"euf_bazooka",
			"euf_constructor",
			"euf_constructor_ai",			
			"euf_marine",
			"euf_priest",
			"euf_pyro",
			"euf_scoutdrone",
			"euf_sniper",
			"euf_sniper_ai",			
			"euf_werewolf",
			"euf_wolf",
			"tc_bonebeast",
			"tc_crawler",
			"tc_enforcer",
			"tc_ghoul",
			"tc_gunner",
			"tc_lich",
			"tc_lich_ai",
			"tc_lich_sum",
			"tc_mage",
			"tc_necromancer",
			"tc_necromancer_sum",
			"tc_pestilence",
			"tc_restless",			
			"tc_rictus",
			"tc_skeleton",
			"tc_undeadmarine_melee",
			"tc_undeadmarine_gun",
			"tc_suicide",
			"tc_witch",
			"tc_witch_shield",
			-- heroes
			"tc_shade",
			"tc_shade_lvl1",
			"tc_shade_lvl2",
			"tc_shade_lvl3",
			"tc_shade_lvl4",	
			"tc_shade_lvl5",
			"euf_sarge",
			"euf_sarge_lvl1",
			"euf_sarge_lvl2",
			"euf_sarge_lvl3",
			"euf_sarge_lvl4",	
			"euf_sarge_lvl5",
			-- neutrals
			"pig"
		},
	
	heavy = {
			"euf_aatower",
			"euf_aatower_survival",
			"euf_aatank",
			"euf_airport",	
			"euf_artytower",			
			"euf_barracks",
			"euf_barracks_ai",			
			"euf_bunker",
			"euf_bunker_ai",			
			"euf_church",	
			"euf_constructor_lvl2",
			"euf_constructor_lvl2_ai",			
			"euf_hover",
			"euf_factory",
			"euf_factory_ai",
			"euf_lasertower",
			"euf_lasertower_ai",
			"euf_metalextractor_lvl1",
			"euf_metalextractor_lvl2",
			"euf_mlrs",
			"euf_mlrs_ai",			
			"euf_paladin",
			"euf_paladin_ai",
			"euf_plasmatower",
			"euf_plasmatower_survival",	
			"euf_powerplant",
			"euf_radar_lvl1",
			"euf_radar_lvl2",
			"euf_raider",
			"euf_sanctum",
			"euf_scorpion",
			"euf_scorpion_ai",			
			"euf_scorpion_burrowed",
			"euf_sensorbot",
			"euf_solar",
			"euf_start",
			"euf_storage",
			"euf_tank",
			"euf_techcenter",
			"euf_techcenter_shield",
			"euf_techcenter_shield_ai",
			"euf_walker",
			"euf_walker_ai",
			"euf_wall_lvl2",
 			"tc_agares",
			"tc_altar",
			"tc_belial",
			"tc_cursedhand",
			"tc_cursedhand_survival",
			"tc_damnedportal",
			"tc_damnedportal_ai",
			"tc_darkassembler",
			"tc_defender",
			"tc_defender_survival",
			"tc_heart",
			"tc_heart_ai",
			"tc_hellfire",			
			"tc_kaboom",
			"tc_mancubus",
			"tc_mermeoth",
			"tc_metalextractor_lvl1",
			"tc_metalextractor_lvl2",
			"tc_obelisk",
			"tc_obelisk_lvl2",
			"tc_purgatory",
			"tc_purgatory_ai",			
			"tc_pyramid",
			"tc_pyramid_ai",
			"tc_soulcage",
			"tc_storage",
			"tc_teeth",
			"tc_teeth_rotated",
			"tc_teeth_rotated2",
			"tc_tower",	
			"tc_tower_survival",		
			"tc_totem_black",
			"tc_totem_purple",
			"tc_totem_red",
			"tc_wall_lvl2",	
			-- neutrals	
			"bug_larva",
			"bug_med",
			"bug_big",
		},
}

-- convert to named maps 
local reverseCompat = (Game.version:find('91.') or (Game.version:find('94') and Game.version:find('94.1.1')== nil)) and 1 or 0
if (reverseCompat > 0) then
	for categoryName, categoryTable in pairs(armorDefs) do
		local t = {}
		for _, unitName in pairs(categoryTable) do
			t[unitName] = 1
		end
		armorDefs[categoryName] = t
	end
end

local system = VFS.Include('gamedata/system.lua')	

return system.lowerkeys(armorDefs)