-- UNITDEF -- TC_LICH --
--------------------------------------------------------------------------------

local unitName = "tc_witch"

--------------------------------------------------------------------------------

local unitDef = {
  acceleration       = 0.75,
  activateWhenBuilt  = true,
  armortype          = "LIGHT",
  brakeRate          = 0.3,
  buildCostEnergy    = 400,
  buildCostMetal     = 400,
  buildDistance      = 200,
  builder            = true,
  buildPic           = "tc_witch.png",
  buildTime          = 400,
  canAssist          = false,
  canAttack          = true,
  canBeAssisted      = false,
  CanCapture         = true,
  canCloak           = true,
  canGuard           = true,
  canManualFire      = true,
  canMove            = true,
  canPatrol          = true,
  canReclaim         = false,
  canRepair          = false,
  canRestore	     = false,
  canResurrect       = false,
  canstop            = "1",
  captureSpeed       = 10,
  category           = "CURSED LAND LIGHTARMOR",
  cloakCost          = 0, --was 40
  cloakCostMoving    = 0, --was 80
  collisionVolumeOffsets 	= "0 0 0",
  collisionVolumeScales 	= "17 33 17",
  collisionVolumeType 		= "CylY",
  -- collisionVolumeTest 		= 1,
  customParams          = {	
	factionname		   = "cursed",
	isinfantry = "true",
	canbetransported = "true",
	mana = 100,
	manaregeneration = 3,
	manacloakcosts = 4,
    helptext = "Witches have two powerful attack spells. The death ray will slow down enemies (movement and attack speed). The Hellstorm is a strong ranged attack. Witches can have two sorts of auras when the proper totems were built by the heart of darkness. The healing aura (heals nearby friendly units) and the curse aura (reduces enemy's accuracy). When a altar of darkness was built wiches can cast a shield spell to protect cursed structures and units."
	},
  defaultmissiontype = "Standby",
  description        = "Spellcaster",
  decloakDistance    = 100,
  --  energyMake         = "-10",
  explodeAs          = "BLOOD_EXPLOSION",
  firestandorders    = "1",
  footprintX         = 2,
  footprintZ         = 2,
  iconType           = "circle",
  idleAutoHeal       = 2.5,
  idleTime           = 400,
  mass               = 550,
  maxDamage          = 1500,
  maxSlope           = 20,
  maxVelocity        = 2.0,
  maxWaterDepth      = 35,
  metalMake          = 0,
  metalStorage       = 0,
  mobilestandorders  = "1",
  movementClass      = "Trooper2X2",
  name               = "Witch",
  nanoColor          = "0.68, 0.31, 0.70",
  objectName         = "tc_witch.s3o",
  onoffable          = false,
  radarDistance      = 768,
  reclaimSpeed       = 0,
  repairSpeed        = 0,
  repairable         = false,     
  resurrectSpeed     = 0,
  script             = 'tc_witch.lua',   
  selfDestructAs     = "BLOOD_EXPLOSION",
  showNanoFrame      = false,
  showNanoSpray      = false,
  side               = "cursed",
  sightDistance      = 512,
  smoothAnim         = false,
  sonarDistance      = 512,
  standingfireorder  = "2",
  standingmoveorder  = "0",
  terraformSpeed     = 0,
  turnRate           = 1500,
  unitname           = "tc_witch",
  upright            = true,
  workerTime         = 10,

  sfxtypes = {
    explosiongenerators = {
      "custom:BLOOD_EXPLOSION",
   	"custom:SPIKES_WITCH", 
    	"custom:SPIKES_WITCH", 
     	"custom:GROUNDFLASH_WITCH", 
   },
  },
  sounds = {
    build              = "",
    canceldestruct     = "",
    repair             = "",
    underattack        = "",
    working            = "",
    arrived = {
      "",
    },
    cant = {
      "",
    },
    count = {
      "",
      "",
      "",
      "",
      "",
      "",
    },
    ok = {
      "",
    },
    select = {
      "witch",
    },
  },
  weapons = {
    [1]  = {
      def                = "WITCHRAY",
      mainDir            = "0 0 1",
      maxAngleDif        = 120,
      onlyTargetCategory = "LAND AIR",
    	},  
     [2]  = {
      def                = "HELLSTORM",
      mainDir            = "0 0 1",
      maxAngleDif        = 180,
      onlyTargetCategory = "LAND",
    	},
  },
}


--------------------------------------------------------------------------------

local weaponDefs = {
  WITCHRAY = {
  
    avoidFeature       = false,
    avoidFriendly      = false,
    avoidneutral       = "0",
    collideFeature     = true,
    collideFriendly    = false,
	
      areaOfEffect            = 14,
      beamTime                = 0.4,
      coreThickness           = 0.5,
      craterBoost             = 1,
      craterMult              = 2,
      energypershot           = 0,
    explosionGenerator = "custom:WITCHRAY",
      fireStarter             = 90,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      largeBeamLaser          = true,
      laserFlareSize          = 5,
      -- lineofsight             = true,
      minIntensity            = 1,
     name               = "witchray",
      --noSelfDamage            = true,
      range                   = 400,
      reloadtime              = 3,
      -- rendertype              = 0,
    rgbColor           = "0.5 0 1",
	scrollSpeed             = 5,
	soundHit           = "witchhit",
	soundHitVolume     = 40,
	soundStart         = "witchshot",
	soundStartVolume   = 40,
	soundTrigger       = false,
      sweepfire               = false,
      targetMoveError         = 0.2,
    texture1           = "soullightning",
    texture2           = "null_texture",
    texture3           = "null_texture",
    texture4           = "flash1",
    thickness          = 4,
      tileLength              = 100,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = "BeamLaser",
      weaponVelocity          = 2250,
    damage = {
	default            = 90,
	flyer              = 90,
	heavy              = 90,
	light              = 90,
    },
  },
  HELLSTORM = {
    accuracy           = 500,
    areaOfEffect       = 175,
    avoidFeature       = false,
    avoidFriendly      = false,
    avoidneutral       = "0",
    burnblow           = false,
    burst              = 4,
    burstrate          = 0.2,
    cegTag             = "HELLSTORM",
	commandFire 	   = true,
    collideFeature     = true,
    collideFriendly    = false,
    collideneutral     = "1",
    collisionSize      = 8,
    craterBoost        = 0,
    craterMult         = 0,
    cylinderTargeting = 0,
    dance              = 66,
    edgeEffectiveness  = 1,
    energypershot      = 0,
    explosionGenerator = "custom:HELLSTORMEXPLOSION",
    explosionSpeed     = 65536,
    fireStarter        = 50,
    flightTime         = 100,
    impulseBoost       = 0,
    impulseFactor      = 0,
    interceptedByShieldType = 2,
    model              = "empty.s3o",
    myGravity          = 0.4,
    name               = "Hellstorm",
    --noSelfDamage       = true,
    range              = 400,
    reloadtime         = 3,
    soundHit           = "hellstorm_hit",
    soundHitVolume     = 160,
    soundStart         = "hellstorm_fire",
    soundStartVolume   = 100,
    soundTrigger       = false,
	sweepFire 			= false,	
    startVelocity      = 400,
    targetBorder       = 0,
    targetMoveError    = 0.1,
    tolerance          = 200,
    tracks             = true,
    turret             = true,
    weaponAcceleration = 400,
    weaponType         = "MissileLauncher",
    weaponVelocity     = 400,
    damage = {
      default          = 220,
      flyer            = 220,
      heavy            = 220,
      light            = 220,
    },
  },
}
unitDef.weaponDefs = weaponDefs


--------------------------------------------------------------------------------

return lowerkeys({ [unitName] = unitDef })

--------------------------------------------------------------------------------
