return {
	pwn     = 'Total Pain',
	bug     = 'Bug Hunter',
	lycan   = 'Werewolf Hunter',
	hover   = 'Hover Admiral',
	air     = 'Airforce General',
	nux     = 'Apocalyptic Achievement Award',
	friend  = 'Friendly Fire Award',
	shell   = 'Turtle Shell',
	fire    = 'Master Grill-Chef',
	emp     = 'Stun Wizard',
	slow    = 'Traffic Cop',
	dran    = 'Dragons & Angels',
	cap     = 'Mind Magician',
	share   = 'Share Bear',
	rezz    = 'Vile Necromancer',
	ouch    = 'Big Purple Heart',
	kam     = 'Kamikaze Award',
	hero    = 'Heros do the job',
	mex     = 'Mineral Prospector',
	mexkill = 'Loot & Pillage',
	herokill = 'Hero Hunter',
	drankill = 'Dragon & Angel Slayer',
	heart   = 'Queen Heart Breaker',
	sweeper = 'Land Sweeper',
}