return {
	pwn     = 'Complete Annihilation',
	navy    = 'Hover Admiral',
	air     = 'Airforce General',
	nux     = 'Apocalyptic Achievement Award',
	friend  = 'Friendly Fire Award',
	shell   = 'Turtle Shell',
	fire    = 'Master Grill-Chef',
	emp     = 'Stun Wizard',
	slow    = 'Traffic Cop',
	t3      = 'Angels & Dragons',
	cap     = 'Mind Magician',
	share   = 'Share Bear',
	rezz    = 'Vile Necromancer',
	ouch    = 'Big Purple Heart',
	kam     = 'Kamikaze Award',
	comm    = 'Heros do the job',
	mex     = 'Mineral Prospector',
	mexkill = 'Loot & Pillage',
	rage    = 'Rage Inducer',
	head    = 'Hero Hunter',
	dragon  = 'Dragon & Angel Slayer',
	heart   = 'Queen Heart Breaker',
	sweeper = 'Land Sweeper',
}